#!/usr/bin/env bash

load() {
    emacs -Q --batch --load epass-json.el --eval '(epass-file-princ-json "~/.passwords")' 2>/dev/null |
        jq -c -r 'select('"$1"')'
}

choose() {
    LINE=$(echo -E "$1" | jq -r -c .name | dmenu -i -1 -p "${2:-select}: " -l 10)
    if [ ! -z "$LINE" ]; then
        echo -E "$1" | sed "${LINE}q;d"
    else
        return 1
    fi
}

case $1 in
    type)
        case $2 in
            user)
                choose "$(load .USERNAME)" "$1 $2" | jq -r .USERNAME | xdotool type --clearmodifiers --file -
                ;;
            password)
                choose "$(load .PASSWORD)" "$1 $2" | jq -r .PASSWORD | xdotool type --clearmodifiers --file -
                ;;
            *)
                DATA=$(choose "$(load '.USERNAME and .PASSWORD')" "$1")
                echo "$DATA" | jq -r .USERNAME | xdotool type --clearmodifiers --file -
                xdotool type --clearmodifiers "	"
                echo "$DATA" | jq -r .PASSWORD | xdotool type --clearmodifiers --file -
                ;;
        esac
        ;;
    visit)
        U=$(choose "$(load .URL)" "$1" | jq -r .URL)
        [ ! -z "$U" ] && xdg-open "$U"
        ;;
    list)
        load . | jq -r .name
        ;;
    echo)
        shift
        output=$1
        shift
        jqrule="true"
        while (( "$#" )); do
            if [ ! -z "$jqrule" ] ; then
                jqrule="$jqrule and "
            fi

            jqrule="$jqrule.${1^^} == \"$2\""
            shift
            shift
        done
        load "$jqrule" | head -n 1 | jq -r ".${output^^}"
        ;;
    *)
        echo "list | type [user | password | both] | visit"
        ;;
esac
