#!/usr/bin/env sh

DEFAULT_SESSION="${HOME}/session"
SESSION="${SESSION_DIR:-$DEFAULT_SESSION}"

cd $HOME

[ -d "${SESSION}" ] || (echo "no ${SESSION}" && exit 1)

nix-env -i lndir
lndir "${SESSION}/dotfiles" .
nix-env -i workspace

# I don't know how to make these work otherwise

cd

ln -sf .nix-profile/share/themes .themes
ln -sf .nix-profile/share/icons .icons

# This setup doesn't work using dotfiles because the modify commands
# erase the symlink. it's also kind of rubbish considering that it
# requires desktop files. On the other hand, one less thing.

xdg-mime default vimb.desktop x-scheme-handler/http
xdg-mime default vimb.desktop x-scheme-handler/https
xdg-mime default vimb.desktop text/html

mkdir -p .zsh
