#!/usr/bin/env sh

SESSION="${HOME}/session"

cd $HOME

[ -d "${SESSION}" ] || (echo "no ${SESSION}" && exit 1)

while read line < "${SESSION}/packages"; do
    nix-env -i "$line"
done

# Now we should have lndir we can put in the files

lndir "${SESSION}/dotfiles" .

# I don't know how to make these work otherwise

ln -sf .nix-profile/share/themes .themes
ln -sf .nix-profile/share/icons .icons

# This setup doesn't work using dotfiles because the modify commands
# erase the symlink. it's also kind of rubbish considering that it
# requires desktop files. On the other hand, one less thing.

xdg-mime default vimb.desktop x-scheme-handler/http
xdg-mime default vimb.desktop x-scheme-handler/https
xdg-mime default vimb.desktop text/html
