#!/usr/bin/env bash
"$SESSION_DIR/scripts/refile" >/dev/null
if [ ! "$?" -eq 0 ]
then
    echo "ERROR: refiler was not happy"
fi

NEW=$(notmuch count tag:new)
SUB=$(notmuch search --format=json tag:new | jq -j '.[0:3]|.[]|.subject+", "')
notmuch tag -new tag:new
notify-send "$NEW new mails" "$SUB"
