#!/usr/bin/env zsh

CHANGED=("${(@f)$($SESSION_DIR/scripts/refile)}")
CHANGED+=(fastmail-inbox)
CHANGED+=(cse:Inbox)
CHANGED+=(cse:JIRA)
typeset -U CHANGED

if [ ! "$?" -eq 0 ]
then
    echo "ERROR: refiler was not happy"
fi

WATCH="$HOME/.mail/last-sync"

if [[ -n "$FULL" ]] || [[ ! -e "$WATCH" ]] || [[ $(date +%s -r "$WATCH") -lt $(date +%s --date="3 hours ago") ]]
then
    echo "full sync"
    E=$(mbsync -q -a 2>&1)
    touch "$WATCH"
else
    echo sync $CHANGED
    E=$(mbsync -q $CHANGED 2>&1)
fi

if [ ! "$?" -eq 0 ]
then
    notify-send -u critical -t 0 "Mail Errors" "$E $CHANGED"
fi
